### ISSUE TITLE
Consider renaming BusinessLogic to Broker

### ISSUE THREAD

**Issue by jmrodri** [pmorie/osb-broker-lib#14]
BusinessLogic is super generic. Consider calling it `type Broker interface`:

https://github.com/openshift/ansible-service-broker/blob/master/pkg/broker/broker.go#L76-L90

**Comment by pmorie** [comment]
I was also considering `broker.Interface` which is probably more idomatic go

**Comment by jmrodri** [comment]
Being more go idiomatic is a fair compromise.
