### ISSUE TITLE
Async bind is not supported, consider feature gates for experimental OSB features?

### ISSUE THREAD

**Issue by eriknelson** [pmorie/osb-broker-lib#23]
[Async Bind](https://github.com/openservicebrokerapi/servicebroker/pull/334) is not currently supported, which is an experimental spec feature the [Automation Broker](https://github.com/openshift/ansible-service-broker) heavily depends on. We need a way to expose the necessary endpoints before we would be able to use the `osb-broker-lib`.

More generically, this begs the question, what is the best way to gate off experimental features of the OSB for users of this library, and allow them to opt into them based on their individual needs?

**Comment by LiliC** [comment]
> More generically, this begs the question, what is the best way to gate off experimental features of the OSB for users of this library, and allow them to opt into them based on their individual needs?

I ran into a similar problem with originating identity feature being disabled by default in the service-catalog. Have no good idea right now, just wanted to say  👍 on this discussion!

**Comment by eriknelson** [comment]
@LiliC Agreed! 

I'm mostly interested in a strategy for this project to handle the more experimental features of OSB. We personally care about async bind, but there will be interesting extensions that will continue to be submitted to the OSB group. It would be nice if broker authors could opt-in to these extensions in an API supported way.
