### ISSUE TITLE
During Testing I would like to be able to check the correct status codes are being set

### ISSUE THREAD

**Issue by shawn-hurley** [pmorie/osb-broker-lib#29]
Currently the testing of the `AlreadyCreated` field is not fully testing the logic that it should. I believe that either the client exposes the HTTP status codes for `2xx` responses or we move from using the client in the test and instead write an `http.Get` to retrieve the status codes.

**Comment by pmorie** [comment]
I would like to maintain the use of the client in the tests, but we can add tests using `http.Get` where we need finer-grained control.
