### ISSUE TITLE
We need a first class way to return OSB errors back to the handler to return the correct http error to the platform

### ISSUE THREAD

**Issue by n3wscott** [pmorie/osb-broker-lib#35]
Current code example is this:

```
response, err := s.Broker.Provision(request, c)
	if err != nil {
		s.writeError(w, err, http.StatusInternalServerError)
		return
	}
```

I have no option to return a bad args error or similar error. Perhaps we wrap error returned from the logic methods with some way to tell the handler method to return OSB errors and we can grab the description from the error returned or something.

**Comment by shawn-hurley** [comment]
I agree, the library should have semantic meaning for certain type of errors that the handler understands and can then return the correct error responses.

**Comment by n3wscott** [comment]
Oh! maybe it is fixed? https://github.com/pmorie/osb-broker-lib/pull/27

**Comment by n3wscott** [comment]
Not fixed yet. #27 was a good first start.

**Comment by n3wscott** [comment]
This works and is good enough for me:

```
				return nil, osb.HTTPStatusCodeError{
					StatusCode:   http.StatusBadRequest,
					ErrorMessage: strPtr("InvalidParameters"),
				}
```
